name: terraform-provider-grafanacloud
on:
  [push, pull_request_target]

jobs:
  label:
    name: Run only when the labels do not include "dependencies"
    runs-on: ubuntu-latest
    steps:
      - name: debug
        run: |
          echo "why wtf"
          echo "${{ toJson(github.event.pull_request.labels.*.name) }}"

  build:
    name: build
    runs-on: ubuntu-latest
#    if: contains(github.event.pull_request.labels.*.name, 'bug')
    steps:
      - name: Setup Go 1.16
        uses: actions/setup-go@v2
        with:
          go-version: 1.16

      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.sha }}

  test:
    name: test
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Test and Build
        run: make deps testacc lint
